### ISSUE TITLE
Issue with folder names and dots

### ISSUE THREAD

**Issue by fterrier** [jonschlinkert/relative#5]
Hi,

We noticed a little issue when using relative and folder names that contain dots.

To reproduce:
1. create a folder with a few dots: `my.super.project` with the file `resources/data/accordion.json` in it
2. execute this:
```
var relative = require('relative');
console.log(relative(process.cwd(), '/Users/username/my.super.project/resources/data/accordion.json'));
```

expected: `resources/data/accordion.json`
result: `my.super.project/resources/data/accordion.json`

**Comment by jonschlinkert** [comment]
Thanks for reporting, I'll look into it

**Comment by dulaccc** [comment]
I can confirm the issue :)
I'll try to make a patch

**Comment by jonschlinkert** [comment]
fixed by https://github.com/jonschlinkert/relative/pull/6
