### ISSUE TITLE
Files at same level don't include preceding dot

### ISSUE THREAD

**Issue by tnrich** [jonschlinkert/relative#7]
If the two files being compared are at the same level in the file structure, the relative path is not preceded by a `./`

For example:

```
 myFolder
   file1
   file2
```

```
var output = relative(file1path, file2path)
console.log(output)
'file2'
```

I would have expected the output to instead be:  `./file2` 

Is there a reason why it isn't like this?

Thanks very much for the otherwise excellent package.

**Comment by tnrich** [comment]
After looking at your tests, it appears that this is the expected behavior. Is there a good way to include the preceding dot + slash if that is desired?

My use case is using it for a node-requirer atom plugin which autocompletes import statements. For the case above, I'd want: `import file2 from './file2'`

**Comment by jonschlinkert** [comment]
> Is there a good way to include the preceding dot + slash if that is desired?

Seems like it should do what you're suggesting. Let me investigate a bit. thanks for creating the issue

**Comment by tnrich** [comment]
Sweet, let me know if you decide to change its behavior.

**Comment by tnrich** [comment]
Any movement on this one @jonschlinkert?

**Comment by jonschlinkert** [comment]
Not yet, but I'd be happy to take a pr if you need something faster

**Comment by tnrich** [comment]
Okay, do we want `./file2` to be the default output for the above example? This makes sense to me.

**Comment by jonschlinkert** [comment]
actually after thinking about this more and doing some comparisons with node.js `path` module to refresh  my memory, `path.normalize` strips the `./` as well. Is there a reason that `./` is expected on the path? sorry, I don't want to belabor the issue, I just don't want to break someone's code

**Comment by tnrich** [comment]
No problem at all. We should definitely make sure this is the behavior that is expected before making it the default. And, if it isn't, it should instead be optional. 

In my use case above, if requiring file2 from file1, I've always preceded the require path with a `./` as I believe this is standard. Eg: `var file2 = require('./file2')`  and not: `var file2 = require('file2')` (no dot-slash indicating an npm package). Does that make sense?

How about we start by optionally including the `./` if something like `includeDotSlashForAllPaths` is passed?

**Comment by jonschlinkert** [comment]
> as I believe this is standard. Eg: var file2 = require('./file2') and not: var file2 = require('file2') (no dot-slash indicating an npm package). Does that make sense?

true, but if you're generating the path a more reliable way to do that is `require(path.resolve('file2'))`. If you're not generating the path, then yes a `./` would be used to prefix the path. 

But since we're generating a relative path, I believe the convention is to remove `./` from the returned path, which is consistent with what `path.relative` does.

**Comment by stevemao** [comment]
@jonschlinkert do you think this should be done in the atom plugin?

**Comment by jonschlinkert** [comment]
@stevemao really sorry, I missed your question. I'm going through all of my open issues and just saw it now. 

> do you think this should be done in the atom plugin?

yes, I think so

**Comment by stevemao** [comment]
@jonschlinkert Thanks. the issue is fixed and should be closed :)

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
